export const workflowDefinitions = [
    {
        id: "project_management",
        name: "Project Management Workflow",
        description: "Comprehensive project planning and tracking",
        intentSignature: {
            primaryDomains: ["project", "planning"],
            secondaryContexts: ["software", "business"],
            complexityLevel: 3,
            requiredCapabilities: ["timeline_planning", "milestone_tracking"],
        },
        triggerKeywords: [
            "project",
            "timeline",
            "milestone",
            "plan",
            "schedule",
            "roadmap",
        ],
    },
    {
        id: "technical_support",
        name: "Technical Support Workflow",
        description: "Troubleshooting and technical problem resolution",
        intentSignature: {
            primaryDomains: ["support", "troubleshooting"],
            secondaryContexts: ["technical", "it"],
            complexityLevel: 4,
            requiredCapabilities: ["diagnostic", "solution_finding"],
        },
        triggerKeywords: [
            "help",
            "problem",
            "issue",
            "error",
            "fix",
            "troubleshoot",
        ],
    },
    {
        id: "legacy_code_refactoring",
        name: "Legacy Code Refactoring Workflow",
        description: "Comprehensive strategy for modernizing and improving existing codebase",
        intentSignature: {
            primaryDomains: [
                "software_engineering",
                "code_quality",
                "modernization",
            ],
            secondaryContexts: [
                "legacy_system",
                "technical_debt",
                "architecture_improvement",
            ],
            complexityLevel: 4,
            requiredCapabilities: [
                "code_analysis",
                "architectural_assessment",
                "incremental_refactoring",
                "dependency_management",
                "regression_testing",
                "performance_optimization",
            ],
        },
        triggerKeywords: [
            "refactor",
            "legacy",
            "modernize",
            "technical debt",
            "improve",
            "restructure",
            "clean code",
            "architecture",
            "upgrade",
        ],
    },
    {
        id: "feature_development_workflow",
        name: "Feature Development and Integration Workflow",
        description: "End-to-end process for designing, implementing, and integrating new software features",
        intentSignature: {
            primaryDomains: [
                "product_development",
                "software_engineering",
                "innovation",
            ],
            secondaryContexts: [
                "feature_design",
                "user_experience",
                "system_enhancement",
            ],
            complexityLevel: 4,
            requiredCapabilities: [
                "requirements_gathering",
                "user_story_mapping",
                "architectural_design",
                "implementation_planning",
                "prototype_development",
                "integration_testing",
                "user_feedback_incorporation",
            ],
        },
        triggerKeywords: [
            "new feature",
            "develop",
            "implement",
            "enhance",
            "add functionality",
            "innovation",
            "product improvement",
            "user story",
            "requirements",
        ],
    },
];
